Repository TCAT-capstone/backend, pull requests merged in 2022-07, with the labels that each got.

#4 [Feat#2] 도메인 개발 및 ticket API 일부 구현
  .gitignore
  src/main/java/return_a/tcat/controller/TicketController.java
  src/main/java/return_a/tcat/domain/Category.java
  src/main/java/return_a/tcat/domain/Member.java
  src/main/java/return_a/tcat/domain/Ticket.java
  src/main/java/return_a/tcat/domain/TicketLike.java
  src/main/java/return_a/tcat/domain/TicketValidation.java
  src/main/java/return_a/tcat/domain/Ticketbook.java
  src/main/java/return_a/tcat/dto/ticket/TicketDto.java
  src/main/java/return_a/tcat/dto/ticket/TicketListResDto.java
  src/main/java/return_a/tcat/dto/ticket/TicketReqDto.java
  src/main/java/return_a/tcat/repository/MemberRepository.java
  src/main/java/return_a/tcat/repository/TicketRepository.java
  src/main/java/return_a/tcat/repository/TicketbookRepository.java
  src/main/java/return_a/tcat/service/TicketService.java
  src/main/resources/application.yml
Labels: ✨feature

#7 [Feat#6] CORS 설정, 요청 camel case로 수정
  src/main/java/return_a/tcat/config/WebConfig.java
  src/main/java/return_a/tcat/dto/ticket/TicketReqDto.java
Labels: 🖼️chore

#9 :sparkles: member, ticketbook, file API개발 및 ticket API수정
  build.gradle
  src/main/java/return_a/tcat/config/AmazonS3Config.java
  src/main/java/return_a/tcat/controller/FileUploadController.java
  src/main/java/return_a/tcat/controller/MemberController.java
  src/main/java/return_a/tcat/controller/TicketController.java
  src/main/java/return_a/tcat/controller/TicketLikeController.java
  src/main/java/return_a/tcat/controller/TicketbookController.java
  src/main/java/return_a/tcat/domain/Member.java
  src/main/java/return_a/tcat/domain/Ticket.java
  src/main/java/return_a/tcat/domain/TicketLike.java
  src/main/java/return_a/tcat/domain/Ticketbook.java
  src/main/java/return_a/tcat/dto/member/MemberDto.java
  src/main/java/return_a/tcat/dto/member/MemberNameResDto.java
  src/main/java/return_a/tcat/dto/member/MemberProfileResDto.java
  src/main/java/return_a/tcat/dto/member/MemberReqDto.java
  src/main/java/return_a/tcat/dto/ticket/TicketDto.java
  src/main/java/return_a/tcat/dto/ticketLike/TicketLikeReqDto.java
  src/main/java/return_a/tcat/dto/ticketbook/TicketbookDto.java
  src/main/java/return_a/tcat/dto/ticketbook/TicketbookListResDto.java
  src/main/java/return_a/tcat/dto/ticketbook/TicketbookReqDto.java
  src/main/java/return_a/tcat/repository/MemberRepository.java
  src/main/java/return_a/tcat/repository/TicketLikeRepository.java
  src/main/java/return_a/tcat/repository/TicketRepository.java
  src/main/java/return_a/tcat/repository/TicketbookRepository.java
  src/main/java/return_a/tcat/service/FileUploadService.java
  src/main/java/return_a/tcat/service/MemberService.java
  src/main/java/return_a/tcat/service/TicketLikeService.java
  src/main/java/return_a/tcat/service/TicketService.java
  src/main/java/return_a/tcat/service/TicketbookService.java
Labels: ✨feature

#13 [Refactor#12] 이미지 url 응답 수정, Ticket 엔티티 수정
  src/main/java/return_a/tcat/controller/FileUploadController.java
  src/main/java/return_a/tcat/domain/Ticket.java
  src/main/java/return_a/tcat/dto/file/ImageDto.java
  src/main/java/return_a/tcat/dto/ticket/TicketDto.java
  src/main/java/return_a/tcat/dto/ticket/TicketReqDto.java
  src/main/java/return_a/tcat/service/FileUploadService.java
Labels: ♻️refactor

#15 [Refactor#17] Ticket 엔티티 및 dto 수정
  src/main/java/return_a/tcat/domain/Ticket.java
  src/main/java/return_a/tcat/dto/ticket/TicketDto.java
  src/main/java/return_a/tcat/dto/ticket/TicketSimpleDto.java
Labels: ♻️refactor

#18 [Feat#17] oauth 로그인 및 회원 프로필 정보 가져오기
  build.gradle
  src/main/java/return_a/tcat/config/AppConfig.java
  src/main/java/return_a/tcat/config/SecurityConfig.java
  src/main/java/return_a/tcat/controller/MemberController.java
  src/main/java/return_a/tcat/domain/AuthProvider.java
  src/main/java/return_a/tcat/domain/Member.java
  src/main/java/return_a/tcat/dto/member/MemberCreateDto.java
  src/main/java/return_a/tcat/dto/member/MemberDto.java
  src/main/java/return_a/tcat/dto/member/MemberProfileResDto.java
  src/main/java/return_a/tcat/dto/member/MemberReqDto.java
  src/main/java/return_a/tcat/exception/BadRequestException.java
  src/main/java/return_a/tcat/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/return_a/tcat/exception/ResourceNotFoundException.java
  src/main/java/return_a/tcat/repository/MemberRepository.java
  src/main/java/return_a/tcat/security/RestAuthenticationEntryPoint.java
  src/main/java/return_a/tcat/security/TokenAuthenticationFilter.java
  src/main/java/return_a/tcat/security/TokenProvider.java
  src/main/java/return_a/tcat/security/UserPrincipal.java
  src/main/java/return_a/tcat/security/oauth2/CustomOAuth2UserService.java
  src/main/java/return_a/tcat/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/return_a/tcat/security/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/return_a/tcat/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/return_a/tcat/security/oauth2/user/GoogleOAuth2UserInfo.java
  src/main/java/return_a/tcat/security/oauth2/user/OAuth2UserInfo.java
  src/main/java/return_a/tcat/security/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/return_a/tcat/service/MemberService.java
  src/main/java/return_a/tcat/util/CookieUtils.java
Labels: ✨feature
